### ISSUE TITLE
Why are we focused on instance variables and hidden methods

### ISSUE THREAD

**Issue by allenwb** [zenparsing/js-classes-1.1#11]
I wanted to capture my answer to this likely question. 

There are many things that third party libraries or transpilers  can do to expend or modify the JS language.  But ultimately they are limited to using the functionality in the standard language that is implemented by the standards conforming engines.   Only TC39 is in a position to strongly nudge implementations into providing new engine-level functionality.

In evolving classes we want to focus on new engine-level capabilities that enhance the utility of JS objects.  Secure instance variables and the ability to securely decompose methods that access them is the key engine-level capability that is currently missing.  Everything else is sugar.

**Comment by zenparsing** [comment]
Closing, as this rationale has been captured in our documentation.
