### ISSUE TITLE
Relation to previous discussions

### ISSUE THREAD

**Issue by littledan** [zenparsing/js-classes-1.1#16]
Hi Allen and Kevin. Thanks for taking the time and effort to write up this proposal. I like how it's understandable and consistent, and how it accomplishes many of the goals that the committee as agreed would be important for classes.

Once convenient property of this proposal is that it doesn't seem to differ radically in its basic model with anything from the current set of class features proposals. For example, instance variables are added "when super returns", just like the current class fields proposal does. It seems that there's a sort of spectrum of possibilities in between the current set of Stage 2/3 proposals and this proposal, and we have a lot of points available in the design space between them.

We've discussed several of these alternatives already during the development of the current class features proposal. To advance your proposal, it might help to discuss these disagreements with the proponents, address these arguments in supporting documents in this repository, and eventually present them to the whole committee. Here, I wanted to give cross-references to those past discussions.

- This proposal seems to eliminate static and instance public field declarations. These have been identified by the committee as important several times, including when the public fields proposal was advanced to Stage 2 individually, and most recently in concerns raised by committee members about not having static public fields at Stage 3. Jeff wrote [a great explainer](https://github.com/tc39/proposal-class-public-fields/blob/4fce08730d273f4c6531021ee7efdc0c5b6591cf/README.md) which goes over the motivation. My understanding is that this proposal eliminates public field declarations based on an idea that they are not a fundamentally new capability; maybe it would be helpful to have a more detailed explanation of why the arguments in favor of the previous proposal were insufficient.
- This proposal gives hidden methods "lexically scoped" semantics, rather than their current semantics where they are similar to private instance fields. Personally, I like these semantics, and for that reason the private methods proposal started with these semantics. However, in the discussion in [this issue](https://github.com/tc39/proposal-private-methods/issues/1) and following discussion at TC39, the rough (though not absolute) consensus seemed to be to use own private field semantics. In conversations I've had with V8 team members, if I understood correctly, it doesn't seem like this will be any slower than public methods (though it does add more complexity to implement). I'd be fine with bringing this issue back to the committee if we should switch to the other semantics. In addition to changing type checking, this would change how private methods are exposed to decorators, so we should come to a conclusion here before moving forward on decorators.
- This proposal makes some significant syntax changes, including `this->x` rather than `this.#x` for instance variable access, `var x;` for instance variable declarations rather than `#x;`, and `hidden method() { }` rather than `#method() { }`. In the discussions about the private fields and methods proposals, we haven't gone into detail in a token like `hidden`, but I thought we've discussed the combination `private x;` and `this->x`. I'm having trouble finding the thread, but I believe a concern about this was that it could lead to a hazard where privacy is surprisingly missing. If a programmer makes a `var x;` declaration, and then just consistently uses `this.x` rather than `this->x`, their code will all just work, except that there won't be any privacy (especially if we don't have any initializers, so they won't even encounter the value surprisingly uninitialized). The risk is especially bad if we use `private` as the sigil, as running unmodified TypeScript code would run straight into this hazard; maybe it's not as bad as with `var` but I'd still be worried about the risk. By contrast, by putting the `#` in both the declarations and usages, programmers can have a mental model that `#` is part of the name, and might be less likely to use the wrong access form.

**Comment by zenparsing** [comment]
Closing in preparation for public review. Please feel free to continue discussion or open a new issue for a specific topic.
