### ISSUE TITLE
Why -> is any better than .#

### ISSUE THREAD

**Issue by allenwb** [zenparsing/js-classes-1.1#19]
In response to @BrendanEich https://github.com/zenparsing/js-classes-1.1/issues/17#issuecomment-370593782 

1. there has been very strong community push back against `#` as a private name prefix. 
2. `.#` is not a single token but is the `.` operator followed by a `#`prefixed identifier. The implication is that `.` is the primary operator.
3. But `.` is not appropriate because the semantics of referencing a hidden name (as defined in this proposal) are not the semantics of property lookup.   This will likely lead to more conceptual confusion about the nature of instance variable, hidden methods, and properties.
4.  Using a distinct operator to dereference a hidden name should help diminish such confusion.
5. There is a limited set of available ascii special characters available for new operators. `->` is an available character combination that carries along a referencing implication from C/C++.
6.  Another possible operator is `..`.  It may be perceived as similar, but different to the `.` operator.  There are both positive and negative conceptual implications of that similarity. 
7. I think `->` reads better (stands out more).  See the example at the start of #5.

**Comment by zenparsing** [comment]
Closing in preparation for public review. Please feel free to continue discussion or open a new issue for a specific topic.

**Comment by Ephys** [comment]
> But . is not appropriate because the semantics of referencing a hidden name (as defined in this proposal) are not the semantics of property lookup. This will likely lead to more conceptual confusion about the nature of instance variable, hidden methods, and properties.

Would such confusion be an actual issue? Do you have an example of something that might not work as expected for a JS developer?
One source of issues I can see is trying to dynamically access a hidden name but I'm pretty convinced developers are going to try to do it with this syntax anyway.

Also, IMHO `->` feels like an alias for `.`, especially given that other languages use it that way. Whereas prefixing with `#` is closer to current community conventions for private state (prefixing with `_`).

**Comment by hax** [comment]
@Ephys 

> but I'm pretty convinced developers are going to try to do it with this syntax anyway.

Why programmers want to try `this['->x']` and expect it return same thing of `this->x`? Or do you mean they will expect `this['x']` return same thing of `this->x`? It's very unreasonable because we already know `this.x` is same as `this['x']`, so if `this.x` is same as `this->x`, what's the purpose of introducing `->`? I don't believe any experienced programmers will think like that.

> Also, IMHO -> feels like an alias for .

If this is your only concern, what do you think about `::` as a replacement of `->`? We also can consider `~>` or `~`. Whichever we choose I believe the syntax issue of this proposal is much much smaller than `#priv`.

> Whereas prefixing with # is closer to current community conventions for private state (prefixing with _).

Unfortunately programmers never think `#` like `_`. We already see the problem of `#` is not technical, but cultural, mental and aesthetic. I gave [a speech introduce `#priv` last year](http://2017.qconbeijing.com/presentation/879) in programming language track of QCon, and most audiences feel terrible with `#`...

> we're trying to access is private or public and use the corresponding operator. An issue # doesn't have (mainly thanks to autocompletion).

This is a minor ergonomics problem of writing code, I don't think it's a big deal, and autocompletion also apply here -- when you enter `this`, autocompletion can list all properties/methods/vars/hidden-methods and other bindings start with `this`.

**Comment by wycats** [comment]
Sorry for jumping in late; I didn't have access to this repository before it was made public.

Most of my programming experience is with Ruby, JavaScript (with some TypeScript) and Rust, so I personally don't have a visceral feel for the `->` operator from significant usage in C or C++.

That said, as @littledan suggested, `x->y` evokes a similar "containment" relationship:

> However, semantically, both operators . and -> have to do with reading/writing named things that relate to an instance.

More specifically, `x->y` does **not** suggest to me that `y` is a lexical variable that is being used as a way to look up a value associated with `x`. The `x.#y` syntax doesn't fare better for me on this front, but this proposed syntax has roughly the same problem for the same reason.

**Comment by hax** [comment]
@wycats 
> but this proposed syntax has roughly the same problem

We always have to choose one syntax... from this *not long* 😉 list:
- `this.@x` Ruby/CoffeeScript style (though it seems very unlikely to happen)
- `this.#x` Current field proposal
- `this->x` C/C++/PHP style
- `this~>x` Variant of `->`
- `this::x` @zenparsing alternative
- `this..x` @allenwb 's old double dot style
- `this~x` Reuse `~` as a binary operator

Which one (or two) do you prefer?

**Comment by allenwb** [comment]
@wycats 
> The x.#y syntax doesn't fare better for me on this front, but this proposed syntax has roughly the same problem for the same reason.

From a purely technical perspective , `.#` as a single token infix operator is equivalent to `->`, `::`, or any other infix operator symbol.  But the current proposals define `.#` is a two token sequence where `#` is prefix character to an _IdentifierName_.  There has been really strong community push back against that prefixing.  The concern doesn't appear to be just with the specific `#` character choice.  There also appears to be a fear that this is just first set towards a family of such name prefixes in the style of BASIC.

Even if we defined `.#` a single token infix operator, that perception would probably persist.

One of our reasons for choosing an operator that doesn't  include `.` is because, as you point out, the treatment of the name to the right of `->` is different then the treatment of the name to the right of `.`.  Neither `->` or `.` are really infix operators.  Instead, both are special forms that impose non-expression semantics on what follows to their right.

A symbol that implies containment is nice, but is unlikely to be universally recognized as such. Ultimately, people have to learn the semantics of these special forms, and intuition is only going to carry them so far.

**Comment by ljharb** [comment]
> There also appears to be a fear that this is just first step towards a family of such name prefixes in the style of BASIC.

@allenwb can you point me to a corpus of pushback that reflects that fear? I've seen, almost universally, a simple dislike of the "#" because it's "ugly". I also don't think that regular developers have a strong sense of "how many tokens are in a sequence" or "somethingfix operator".

**Comment by hax** [comment]
@ljharb 
Yes people don't matter "somethingfix operator". 

But `#` in `#x` is *not* a operator. When you mean operator, `x` in `x+y` should convey the same meaning of `x` in `#x`. But it's not, `#x` should be understand as a special identifier which very different to `x`. I think this bring people a big strangeness.
