### ISSUE TITLE
Presentation/feedback plan

### ISSUE THREAD

**Issue by littledan** [zenparsing/js-classes-1.1#20]
Given how V8 has a complete implementation of the class fields proposal behind a flag, test262 has pretty complete tests checked in, and that proposal has been at Stage 3 for several months after years of committee deliberation, I'd like to come to a conclusion on whether the committee is interested in switching to a proposal like this pretty soon. Would it make sense to share this proposal publicly to get broader feedback on it?

TC39 has already considered several of the aspects of this proposal, as I documented in #16. The champions of this proposal have explained their opinions on class features to the committee in the past, and this proposal seems like a nice, coherent embodiment those preferences. Nevertheless, despite being aware of these arguments, TC39 confirmed the proposals in their current state several times, through repeated stage advancement. I can see how there's internal synergy within this proposal, but I don't see how there's *more* synergy than in the current set of class proposals.

I'm interested in your perspective on how this proposal interacts with the TC39 stage process. Brendan [has mentioned a possible process foul](https://twitter.com/BrendanEich/status/947271505695539200) if someone wanted to re-litigate the motivation of decorators, a Stage 2 proposal with no implementations, not even transpilers, for the current semantics. (This all turned out to be a misunderstanding, and I hope you all enjoyed Yehuda, Caridy and Diego's presentation as much as I did.) This proposal removes static public fields, which is at Stage 3. If debating decorator motivation would be a process foul, how would you justify the discussion about public fields?

Going by aspects, here are some concerns I have about how these issues could be re-raised:
- This design is based on the idea that we should focus on only things which add core capabilities, and not which could be done through a transpiler. TC39 considered and rejected this argument with respect to decorators, and advanced them to Stage 2 as a result. What are the grounds for reconsidering this decision?
- Public fields (including static public) are very widely requested by the community, and the proposed semantics are simple and readily implementable. I don't see a good reason to withdraw the proposal.
- The `->` syntax doesn't meet the requirements we set for ourselves when deciding on `.#`, including reducing the risk accidentally leaking private fields, and allowing for a shorthand syntax without various kinds of hazards. It's true that there's angst in the community reception of the private fields proposal, but I don't see that angst pointing clearly in this direction. For one, we know that there will be a camp that's unhappy if instance variables are not like TypeScript private.
- Many TC39 members prefer the current private methods semantics over the lexically scoped function semantics. I've asked a few people again what their thoughts are on this to confirm, and it seems like it would be difficult to get consensus on this change.
- We considered a declaration syntax with a token at the beginning at length. We had a lot of discussion and different arguments brought up, and over multiple meetings, we eventually got consensus on not having a token at the beginning. This proposal adds a token again; I don't think it'll be trivial to get consensus on either the existence of a token or the choice (given that ES6 has led to a "var is bad" meme).

**Comment by zenparsing** [comment]
Closing in preparation for public review. Please feel free to continue discussion or open a new issue for a specific topic.

**Comment by wycats** [comment]
In light of the significance of this proposal and how much it affects other class-related proposals submitted for advancement at the March meeting, I'm disappointed that this repository remained private until so recently.

As a co-champion of a part of the status quo class suite, I would have welcomed the opportunity to provide feedback on this proposal ahead of the public release.

I'll try to provide written feedback as much as possible ahead of the meeting, so that the meeting itself can productively focus on areas of agreement and disagreement.

Out of curiosity, how do @allenwb and @zenparsing (as well as @BrendanEich and @erights, who also seem enthusiastic about this proposal) feel we should stage the discussion about it relative to the tactical presentations about the status quo proposals? Should we discuss this proposal first?
