### ISSUE TITLE
AWB alternative 2 - instance vars and secret methods

### ISSUE THREAD

**Issue by allenwb** [zenparsing/js-classes-1.1#7]
### Max-min classes 1.1.  AWB alternative 2

_An updated version of this proposal is below at https://github.com/zenparsing/js-classes-1.1/issues/7#issuecomment-362840196_

Here is a proposal that is closer to the @zenparsing  parsing original, but perhaps simpler.  With this proposal, I don't necessarily see the need for a classes 1.2 follow-on

# Basic Concepts
- This proposal adds the concept of secret class elements to ECMAScript class definitions. Secret class elements are only accessabe from within the body of a class definition.
- There are three kinds of secret class element, static initializer blocks, instance variable definitions, and secret method definitions.
- A class definition may contain at most one static initializer block it is automatically executed as the final step of class def evaluation
  - The static initializer block is a secret of the class definition, there is no way to invoke it from outside of the class definition
- A instance variable definition defines one or more secret variables that exist in each instance of a class. 
  - An instance variable defnition within a class body looks like this:
  ```js
  var x,y;  //each instance created by this class constructor will have these two instance variables
  ```
  - Within a class body, instance variables are accessed using the -> operator like this:
  ```js
  this->x = 0;
  console.log(obj->y);
  ```
  - Instances variable names are lexically scoped and visible to everything contained in a class body.
  - Attempting to access an instance variable using -> produces a runtime ReferenceError if the object does not have the specific named instance variable defined by this class definition.  In other words, A reference to an instance variable only works when the objectise a normally constructed instance of this class or one of its subclasses. 
  - Instance variable definitions don't have initializers. Instance variables are usually initialized by the constructor. An uninitialized instance variable has the value `undefined`.
- A secret method definition is a concise method that can only be directly involked from inside the class body.
  - A secret method definition looks exactly like a concise method except its name is prefixed by `->`
  - Here are some examples of secret method definitions
  ```js
  ->foo() {return super.bar()}
  get ->x() {return this->_x}  //a secret accessor method
  set ->x(v) {this->_x = v}
  ```
  - Secret method names are lexically scoped and visible to everything contained in a class body.
  - Within a class body, secret methods are invoked using the -> operator like this:
  ```js
  this->foo();
  obj->x = 5;   //invokes a secret set accessor method
  this->foo.bind(this);  //access the function value of a secret method
  ```
  - Secret methods can be accessed/invoked with any object supplied to the left of the `->`. It is up to the code of the method body whether or not a runtime error will occur if the `this` value is not an instance of the containing class or one of its subclasses. Access to instance variables that don't exist for the `this` value would, of course, throw.
- It is an early error if the name occuring to the right of a `->` operator is not the lexically visible name of a secret method.
- No reflection on instance variables, instance variable names, secret methods, or secret method names
- Lexically scoped instance variable and secret method declarations introduce new names into a parallel scope (does not shadow non-secret names)

# Example
```js
class Point {
   var x;    //or:  var x, y;
   var y;  
   
   ->brandcheck() {
      try {this->x} catch {return false};
      return true;
   }
       
   get x() {return this->x} //normal accessor properties
   get y() {return this->y}
   
   add(another) {  //a normal method property
      if (another.brandcheck()) 
        return new Point(this->x+another->x, this->y+another->y);
      else 
        return new Point(this->x+another.x, this->y+another.y);
   }
   
   constructor (x,y) {
      this->x = x;
      this->y = y;
   }
}
```

# Technical Notes and Rationale
- `var` is repurposed to declare instance variables because its name is suggestive of "instance VARiable".  Note that several early ES class proposals including the original ES4 proposals used `var` for this purpose.
- Secret names (instance variables and secret methods) exit in the same namespace so an instance variable may not have the same name as a secret method.
- The kind of thing a secret name is bound to is based upon its declration.  -> may statically determines from the supplied name whether it is accessing an instance variable, a secret accessor method, or invoking a secret method.
- Any  concise method form may be used to define a secret method.  It's the -> prefix to the name that makes it a secret method.
- Secret methods don't have any special semantics for their bodies. The Home object of a secret method is the prototype object defined by the class.
- There is no particular reason why we couldn't have `static` instance variables and `static` secret method definitions.  But it is simplier to not have to explain how they differ from the non-static forms.
- Instance variable declrations do not have initializers to simplify things.  Without them, we don't have to define their evaluaiton order or the scoping of the initializer expressions.  People are already used to using constructors to initialize instance state.
- It is an early error to assign to a secret method reference (unless it is an accessor method)
- Because secret methods are statically resolvable and immutable, it is easy for an implementation to statically in-line them.  No flow analysis or dynamic specialization required.
- The `var` declarations of a class collective and statically defined the "shape` of the secret instance state introduced by that class definition. Subclass can add additional secret state "shapes" but overall it is a step closer to objects with a fixed shape determined at class definition time and should also make it easier to lift the internal checks needed on instance var accesses.

**Comment by allenwb** [comment]
@erights
> I find the visual scope confusion at #7 (comment) caused by var x; to be terrible.

In practice, I don't think that will occur very often.  Programmer who know modern JS well enough to code a class with instance variables will also know that `let` is the modern way to declare lexical variables.

However, we could eliminate any such possibility, by defining a static semantic rules that says that it an early error to define a instance variable named `x` in a class definition that is lexically nested in a scope that has visibility of a legacy `var x;` variable declaration.

Such rules would add some complexity to the spec. and that is something we are trying to avoid. But it could be done.  Part of what we are reacting to with this proposal in the growing conceptual and actual complexity of recent proposals. Essential complexity is, well, essential. But accumulating inessential complexity is detrimental.  It would be terrible if someone actually wrote something like:
```js
var x;
class foo {
  var x;
  get x() {return this->x}
}
```
But is it worth adding complexity (and actual runtime work) to detect and reject it?

**Comment by zenparsing** [comment]
Closing in preparation for public review (we want reviewers to focus on the proposal materials rather than long issue threads). Please feel free to continue discussion here or open a new issue for a specific topic.

**Comment by littledan** [comment]
> The usage of -> :: in other languages are close to property/name lookup which make them look "correct"

Several comments from @allenwb and @zenparsing seem to be based around an idea that `->` makes it more clear than `.#` that this is *not* property access. That distinction would help explain why the semantics are different from property access. Does this have the potential to be confusing, given @hax 's intuition above?

**Comment by allenwb** [comment]
@littledan 
I don't think so.  `->` or `::` is a form of lookup in other language but in those language neither has the same semantics that they give to `.`

That is all we were saying, -> is an accessor operator that is different from the `.` or `[]` property access operators.  It is different in both what it accesses and how it does its lookup.

Regarding, using `::` instead of `->`.  It was a close 2nd choice in our design discussions.  I wouldn't be upset if we concluded there was a good reason to switch to it.

**Comment by Jamesernator** [comment]
I quite like the idea of closure-like variables instead of having to worry about things like "writable"/"configurable" (like-properties) that private fields would allow in the current specification.

It would be nice though if these are variable-like to be able to have them  be *actually* variable-like and allow `let`/`const` variables somehow. I wonder if class-parameters could be revived to do this e.g.:

```js
class Vector(x, y) {
    const ->x = x
    const ->y = y

    /* No constructor */
    
    add(otherVector) {
        return new Vector(this->x + other->x, this->y + other->y);
    }

    get x() {
        return this->x
    }

    get y() {
        return this->y
    }
}

new Vector(3, 4);
```

Another example with a constructor as well:

```js
class Adder extends HTMLElement {
    const ->shadowRoot = this.attachShadow({ mode: 'closed' })
    let ->count = 0

    constructor() {
        this->shadowRoot.innerHTML = someTemplate;
        this->shadowRoot.querySelector("#clickMe").onclick = _ => {
            this->count += 1
            this->render()
        }
        this->render()
    }

    hidden render() {
        const countElem = this->shadowRoot.querySelector("#countOut")
        countElem.innerHTML = this->count
    }
}
```

**Comment by hax** [comment]
@Jamesernator 
Do you mean use class-parameters replace constructor? Use two syntax do the same thing sounds not a good idea to me.

About `const/let`, see #25

**Comment by Jamesernator** [comment]
The main reason for suggested class-parameters is because `const`/`let` are traditionally block-scoped, `const ->shadowRoot = this.attachShadow({ mode: 'closed' })` wouldn't allow the declaration of `->shadowRoot` to appear in the top-level. Perhaps it's not actually that confusing though if it was in the constructor:

```js
class Adder extends HTMLElement {
    constructor() {
        const ->shadowRoot = this.attachShadow({ mode: 'closed' })
    }

    hidden render() {
        // Is it confusing that `const ->shadowRoot` isn't block-scoped
        // to the constructor function? Probably not to be honest
        // after using it a couple times
        const countElem = this->shadowRoot.querySelector("#countOut")
    }
}
```

I'll continue discussion on #25 though.
