### ISSUE TITLE
Hidden members in object literals?

### ISSUE THREAD

**Issue by allenwb** [zenparsing/js-classes-1.1#8]
It would seem that  instance variables and hidden methods from #7 could be easily adapted to object literals.  Consider:
```js
function makePoint(x,y) {
   return {var x: x,
           var y: y,
           get x() {return this->x),
           get y() {return this->y),
           set x(v) {if (this->isMutable()) this->x = v},
           set y(v) {if (this->isMutable()) this->y = v},
           hidden isMutable() {returnDate().getDay() == 2),
           ...
   }
}
```
or alternatively
```js
function makePoint(x,y) {
   return {->x: x,
           ->y: y,
           get x() {return this->x),
           get y() {return this->y),
           set x(v) {if (this->isMutable()) this->x = v},
           set y(v) {if (this->isMutable()) this->y = v},
           ->isMutable() {returnDate().getDay() == 2),
           ...
   }
}
```              
I think this might be a further selling point to this approach.  Programmers who prefer object literals to class definitions also get functionality of hidden state and methods .

**Comment by zenparsing** [comment]
> What if we get rid of hidden methods, allow lexical functions inside classes (even if it is only functions), and re-introduce infix `::`?

That was exactly the solution that I presented in Paris in 2015. If I recall correctly, there was significant push-back against using function declarations as internal methods in this way. At the time (and I believe this is still the case), there was concern about relying so heavily on `this` outside of a proper method context. It was argued that such "profligate" `this` usage would be confusing to users that already find `this` a bit confusing.

There are other advantages to using `hidden` methods over lexical function declarations:

- We avoid having two kinds of function definition forms in class bodies.
- Users can easily refactor from normal method code to hidden method code, even in the case of accessors.
- Hidden methods can contain `super` references, correct for the containing method placement (either prototype or `static`).

> `::` gives us lots more functionality at a small differential cost.

The added functionality is the ability to support "extension" methods outside of class contexts. I would still like to see us explore the extension method idea, but in a way that does not run afoul of the concerns above.

**Comment by allenwb** [comment]
> Recently, a few people including Justin, Axel and Yehuda have been discussing how to move forward on private name declarations outside of classes. 

This is just one example of what the Max-min Classes 1.1 proposal is reacting to.  TC39 currently has an continuing stream of actual and potential class  related proposals, each  having  to fit in with already committed proceeding proposals.  (I call that "kick the ball down the field design") Instead we suggest that we identify and provide  the most minimal set of essential functionality that is still missing from class definitions.  Then stop! Be finished with classes for the next 10 years. 

JS has always been a minimalist language.

**Comment by zenparsing** [comment]
Closing in preparation for public review. Please feel free to continue discussion or open a new issue for a specific topic.
