### ISSUE TITLE
A way to explain hidden names and the -> operator

### ISSUE THREAD

**Issue by allenwb** [zenparsing/js-classes-1.1#9]
We shouldn't be overly concerned about people getting confused about lexical variable/function and hidden name bindings.   We already have something very similar in the language and people are used to dealing with it just fine.

Consider:
```js
let p = {x:0,y:0};
p.x=1;
var x=p;
console.log(x);
console.log(x.x);
console.log(p.x);
```
JS programmers understand  what `x`  or `p` standing alone means and they understand that `x` on the left of the `.` meanings something completely different from `x` to the right of `.`.  They understand that the `x` on the right is converted to a string value which is then used to as a key to attempt to access a property of the object referenced by `x` on the left.

Similarly, when a programmer learns about `->` they will also learn that the `x` on the left of the `->` meanings something completely different from `x` to the right of `->.`.  They will learn that that the `x` on the right is converted to special internal hidden name key that is defined by the enclosing class and which is used to attempt to access a hidden value of the object reference by the `x` on the left.

```js
x;
o.x;
o->x;
```
They all interpret `x` differently and the syntax tells the reader which interpretation applies in each case.

This is why we should never  have any sort of implicit property or hidden value access that just uses an unqualified identifier. If we did, then:
```js
x;
x;
x;
```
could mean three completely different things.  Even with the encompassing  contextual declarations that would have to be there to disambiguate them, a reader of a simple line of code would never know for sure what that `x` means.

**Comment by zenparsing** [comment]
Closing in preparation for public review.
